name: Dispatch test & release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test

jobs:
  dispatch:
    name: Test run
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && exit 1
