name: Dispatch test & release

on:
  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.event.client_payload.number || github.event.client_payload.ref }}
jobs:
  unit-tests-and-lint:
    name: Unit tests and lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          fetch-depth: 0
          repository: ${{ secrets.REPOSITORY }}
          ref: ${{ github.event.client_payload.github.ref }}

      - run: ls -a
